MoneyBudgets/Controllers/AccountTypeController.cs
using Microsoft.AspNetCore.Mvc;
using MoneyBudgets.Interfaces;
using MoneyBudgets.Models;
using System.Diagnostics;

namespace MoneyBudgets.Controllers
{
    public class AccountTypeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IAccountTypeService _accountTypeService;
        private readonly IUsersService _usersService;
        public AccountTypeController(ILogger<HomeController> logger, IAccountTypeService accountTypeService, IUsersService usersService)
        {
            _logger = logger;
            _accountTypeService = accountTypeService;
            _usersService = usersService;
        }

        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> IndexAsync()
        {
            var id = _usersService.GetUserId();
            var accountTypes = await _accountTypeService.GetAccountsbyUser(id);


            return View(accountTypes);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AccountTypeModel account)
        {
            if (!ModelState.IsValid)
            {
                return View(account);

            }
            // TODO- Make users and quit this mock example
            account.UserId = _usersService.GetUserId();

            bool exists = await _accountTypeService.ExistsAccount(account.Name,account.UserId);

            if (exists)
            {
                ModelState.AddModelError(nameof(account.Name), $"Account type {account.Name} already exists");

                return View(account);
            }

            await _accountTypeService.AddAccountType(account);

            return RedirectToAction("Index");
        }

        [HttpGet]

        public async Task<IActionResult> ValidateIfExists(string name)
        {
            // TODO- Make users and quit this mock example
            var id = _usersService.GetUserId();
            var existsAccount = await _accountTypeService.ExistsAccount(name, id);

            if(existsAccount) {
                return Json($"Name {name} already exists");
            }

            return Json(true);
        }

        [HttpGet]

        public async Task<IActionResult> Edit(int id)
        {
          
            var userId = _usersService.GetUserId();
            var accounttype = await _accountTypeService.GetAccountbyUserAndId(userId, id);

            if (accounttype is null)
            {
                return RedirectToAction("NotExists", "Home");
            }

            return View(accounttype);
        }

        [HttpPost]

        public async Task<IActionResult> Edit(AccountTypeModel accountType)
        {

            var userId = _usersService.GetUserId();
            var accounttype = await _accountTypeService.GetAccountbyUserAndId(userId, accountType.Id);

            if (accounttype is null)
            {
                return RedirectToAction("NotExists", "Home");
            }

            await _accountTypeService.UpdateAccountType(accountType);

            return RedirectToAction("Index");
        }

        [HttpGet]

        public async Task<IActionResult> Delete(int id)
        {

            var userId = _usersService.GetUserId();
            var accounttype = await _accountTypeService.GetAccountbyUserAndId(userId, id);

            if (accounttype is null)
            {
                return RedirectToAction("NotExists", "Home");
            }

            return View(accounttype);
        }

        [HttpPost]

        public async Task<IActionResult> DeleteAccountType(int id)
        {

            var userId = _usersService.GetUserId();
            var accounttype = await _accountTypeService.GetAccountbyUserAndId(userId, id);

            if (accounttype is null)
            {
                return RedirectToAction("NotExists", "Home");
            }

            try
            {
                await _accountTypeService.DeleteAccountType(userId, id);
            }
            catch(Exception ex)
            {
                {
                    TempData["error"] = "An error occurred: " + ex.Message;
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]

        public async Task<IActionResult> OrderAccounts([FromBody] int[] ids)
        {
            var userId = _usersService.GetUserId();
            List<AccountTypeModel> accounttypes = await _accountTypeService.GetAccountsbyUser(userId);

            var accountsIdsToOrder = accounttypes.Select(x => x.Id);

            var IdsNotSameUser = accountsIdsToOrder.Except(ids).ToList();

            if(IdsNotSameUser.Count > 0)
            {
                return Forbid();
            }

            var accountsOrdered = ids.Select((value,index) => 
            new AccountTypeModel() { Id = value, Order = index + 1}).AsEnumerable();

            await _accountTypeService.OrderAccounts(accountsOrdered);

            return Ok();
        }
    }
}

MoneyBudgets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoneyBudgets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MoneyBudgets.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MoneyBudgets</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="AccountType" asp-action="Index">Account Type</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Index">Account</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Toast" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MoneyBudgets - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MoneyBudgets/Views/Shared/_Resultado.cshtml
@model string

<h1>Resultado</h1>

<div>
    <label for="resultado">Resultado:</label>
    <input type="text" readonly value="@Model" />
</div>

MoneyBudgets/Views/Shared/_Toast.cshtml
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />


@if (TempData["error"] is not null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}


@if (TempData["success"] is not null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}